spring:
  application:
    name: mybatis-plus-practice
  datasource:
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: root
    password: password
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    com.shenjies88.practice.mybatispluspractice: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: ignored




